// <auto-generated />
namespace Movie_Rentals.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Incert_NameOfMEmbershipType : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Incert_NameOfMEmbershipType));
        
        string IMigrationMetadata.Id
        {
            get { return "202002141517412_Incert_NameOfMEmbershipType"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
